<a href="https://colab.research.google.com/github/Shresta0506/shresta_INFO5731_Spring2026/blob/main/In_Class_Exercise_Combined_8_and_9_shresta_panyala_ipynb__281_29%2B_281_29%2B_282_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In-Class Exercise: Sentiment Analysis + Text Classification + Prompt Engineering

**Course:** NLP / Text Mining  
**Total Points:** 30  
**Suggested Time:** about 45 minutes total  
**Dataset:** `sentiment_classification_combined_data.csv`

**Instructions**
- Complete all questions in this notebook.
- Run all cells before submission.
- Keep your answers clear and organized.
- For the prompt engineering part, you do **not** need an API key.

## Part A — Sentiment Analysis with VADER (10 points)
In this part, use **VADER** to compute sentiment scores for the text data.

In [1]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving sentiment_classification_combined_data.csv to sentiment_classification_combined_data (1).csv
Uploaded file name: sentiment_classification_combined_data (1).csv

### Q1. Load and inspect the dataset (2 points)
Show:
1. the first 5 rows  
2. the shape of the dataset  
3. the column names

In [2]:
# Read the uploaded CSV file
import pandas as pd

df = pd.read_csv(filename)

# 1. First 5 rows
print("First 5 rows:")
display(df.head())

# 2. Shape
print("Shape of dataset:", df.shape)

# 3. Column names
print("Column names:")
print(df.columns.tolist())

First 5 rows:

                                                Text TrueLabel  Score
0  I loved this healthcare AI workshop. The examp...  positive      5
1  This lecture was okay, but some parts were con...   neutral      3
2  The notebook was easy to follow and very pract...  positive      5
3  I did not like the explanation of the model re...  negative      1
4  The activity was interesting and helped me und...  positive      4

Shape of dataset: (24, 3)
Column names:
['Text', 'TrueLabel', 'Score']

### Q2. Apply VADER to compute sentiment scores (3 points)
- Import VADER
- Download the lexicon if needed
- Create a new column called `compound`
- Show the first 5 rows of `Text` and `compound`

In [4]:
!pip -q install nltk
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [5]:
# Create compound sentiment score using VADER
df['compound'] = df['Text'].astype(str).apply(lambda x: sia.polarity_scores(x)['compound'])

# Show first 5 rows of Text and compound
df[['Text', 'compound']].head()

                                                Text  compound
0  I loved this healthcare AI workshop. The examp...    0.8555
1  This lecture was okay, but some parts were con...   -0.2263
2  The notebook was easy to follow and very pract...    0.4404
3  I did not like the explanation of the model re...   -0.2755
4  The activity was interesting and helped me und...    0.4019

### Q3. Create a sentiment label from the compound score (3 points)
Create a new column called `PredictedSentiment` using this rule:
- `compound >= 0.05` → `positive`
- `compound <= -0.05` → `negative`
- otherwise → `neutral`

Then show the first 10 rows of `Text`, `compound`, and `PredictedSentiment`.

In [6]:
# Create PredictedSentiment column based on compound score
def get_sentiment_label(compound):
    if compound >= 0.05:
        return 'positive'
    elif compound <= -0.05:
        return 'negative'
    else:
        return 'neutral'

df['PredictedSentiment'] = df['compound'].apply(get_sentiment_label)

# Show first 10 rows
df[['Text', 'compound', 'PredictedSentiment']].head(10)

,Text,compound,PredictedSentiment
0,I loved this healthcare AI workshop. The examp...,0.8555,positive
1,"This lecture was okay, but some parts were con...",-0.2263,negative
2,The notebook was easy to follow and very pract...,0.4404,positive
3,I did not like the explanation of the model re...,-0.2755,negative
4,The activity was interesting and helped me und...,0.4019,positive
5,The class was too fast and I could not follow ...,0.0000,neutral
6,"The topic is important, but the instructions w...",0.1027,positive
7,I really enjoyed the examples and the live cod...,0.5563,positive
8,The dataset was messy and the task felt frustr...,-0.6597,negative
9,The exercise was manageable and useful for pra...,0.4404,positive

### Q4. Compare review score and sentiment (2 points)
Group by `Score` and compute the **average compound score** for each score value.

In [7]:
result = df.groupby('Score')['compound'].mean().reset_index()
result.columns = ['Score', 'Avg_Compound_Sentiment']
result

   Score  Avg_Compound_Sentiment
0      1               -0.507033
1      2               -0.296125
2      3               -0.150783
3      4                0.478340
4      5                0.621167

## Part B — Prompt Engineering (10 points)
This part is based on the **Prompt Engineering** notebook. You do **not** need an API key. Focus on writing better prompts using the concepts of **instruction, context, output format, zero-shot, few-shot, and chain-of-thought**.

In [ ]:
# Sample texts for the prompt engineering questions
sample_reviews = [
    "The product arrived late and the quality was poor.",
    "Amazing battery life and elegant design.",
    "It is fine for daily use, nothing special."
]
for i, text in enumerate(sample_reviews, start=1):
    print(f"{i}. {text}")

### Q1. Zero-shot classification prompt (3 points)
Write a **zero-shot prompt** that asks an AI model to classify each review as **positive, negative, or neutral**.

Your prompt should include:
- a clear instruction
- the three labels
- a request for a clean output format

Store your prompt in a Python variable called `zero_shot_prompt`, then print it.

In [9]:
zero_shot_prompt = """
You are given a set of customer reviews. Your task is to determine the sentiment expressed in each review.

Possible sentiment labels:
- Positive
- Negative
- Neutral

Guidelines:
- Choose only one label per review
- Base your decision on the overall tone of the sentence

Output requirements:
Provide only the sentiment labels in a numbered list format as shown below:
1. label
2. label
3. label

Reviews to analyze:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

print(zero_shot_prompt)

You are given a set of customer reviews. Your task is to determine the sentiment expressed in each review.

Possible sentiment labels:
- Positive
- Negative
- Neutral

Guidelines:
- Choose only one label per review
- Base your decision on the overall tone of the sentence

Output requirements:
Provide only the sentiment labels in a numbered list format as shown below:
1. label
2. label
3. label

Reviews to analyze:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q2. Few-shot prompt improvement (3 points)
Now improve the previous prompt by adding **two examples**.

Requirements:
- Store it in a variable called `few_shot_prompt`
- Include 2 input-output examples
- Ask the model to classify the 3 sample reviews after the examples

In [10]:
few_shot_prompt = """
You are an AI system that analyzes customer opinions and determines their sentiment.

Sentiment categories:
- Positive
- Negative
- Neutral

Instructions:
- Read each review carefully
- Decide the overall sentiment
- Assign only one label per review

Examples:

Review: "The phone works perfectly and I absolutely love it."
Sentiment: Positive

Review: "The item stopped working after one day and support was useless."
Sentiment: Negative

Now classify the following reviews:

Output format:
Provide only the sentiment labels in a numbered list:
1. label
2. label
3. label

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

print(few_shot_prompt)

You are an AI system that analyzes customer opinions and determines their sentiment.

Sentiment categories:
- Positive
- Negative
- Neutral

Instructions:
- Read each review carefully
- Decide the overall sentiment
- Assign only one label per review

Examples:

Review: "The phone works perfectly and I absolutely love it."
Sentiment: Positive

Review: "The item stopped working after one day and support was useless."
Sentiment: Negative

Now classify the following reviews:

Output format:
Provide only the sentiment labels in a numbered list:
1. label
2. label
3. label

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q3. Prompt comparison and refinement (4 points)
Create a short table or DataFrame with **three columns**:
- `PromptType`
- `MainFeature`
- `WhyUseful`

Include these three prompt types:
1. Zero-shot
2. Few-shot
3. Chain-of-thought

Then, in **2–3 sentences**, explain which one you would choose for a more difficult text analysis task and why.

In [11]:
import pandas as pd

prompt_comparison = pd.DataFrame({
    "PromptType": ["Zero-shot", "Few-shot", "Chain-of-thought"],
    "MainFeature": [
        "Uses only instructions without any examples",
        "Provides sample input-output pairs before the task",
        "Encourages reasoning through intermediate steps"
    ],
    "WhyUseful": [
        "Quick to use and works well for simple tasks",
        "Improves accuracy by showing expected patterns",
        "Helps break down complex problems step by step"
    ]
})

display(prompt_comparison)

print("""
For more difficult text analysis tasks, I would choose few-shot or chain-of-thought prompting.
Few-shot is helpful because the examples guide the model toward the correct pattern, improving accuracy.
Chain-of-thought is useful when the task involves deeper reasoning, as it allows the model to process the problem step by step.
""")

,PromptType,MainFeature,WhyUseful
0,Zero-shot,Uses only instructions without any examples,Quick to use and works well for simple tasks
1,Few-shot,Provides sample input-output pairs before the ...,Improves accuracy by showing expected patterns
2,Chain-of-thought,Encourages reasoning through intermediate steps,Helps break down complex problems step by step

For more difficult text analysis tasks, I would choose few-shot or chain-of-thought prompting.
Few-shot is helpful because the examples guide the model toward the correct pattern, improving accuracy.
Chain-of-thought is useful when the task involves deeper reasoning, as it allows the model to process the problem step by step.

## Reflection (optional, no extra points)
Briefly explain the difference between:
- sentiment analysis
- text classification
- prompt engineering

Sentiment analysis is basically about figuring out the feeling behind a text, like whether it’s positive, negative, or neutral. You usually see this in things like reviews or comments.

Text classification is more general. It means putting text into different categories based on what it’s about, like spam vs not spam, topic classification, or even sentiment. So sentiment analysis is actually one type of text classification.

Prompt engineering is about how we ask questions or give instructions to AI so it gives better answers. If we write the prompt clearly with proper instructions or examples, the output becomes much more accurate.